/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['Hello World!'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n'])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),0,'hr',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(5,0,(null as any),(null as any),
      2,'a',[['routerLink','/']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,6).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(6,671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted(-1,(null as any),['Home'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n'])),(_l()(),i1.ɵeld(9,0,(null as any),(null as any),2,'a',
      [['routerLink','/users']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,10).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(10,671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted(-1,(null as any),['Users'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n'])),(_l()(),i1.ɵeld(13,0,(null as any),(null as any),0,'hr',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(15,16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(16,212992,(null as any),
          0,i2.RouterOutlet,[i2.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    const currVal_2:any = '/';
    _ck(_v,6,0,currVal_2);
    const currVal_5:any = '/users';
    _ck(_v,10,0,currVal_5);
    _ck(_v,16,0);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,6).target;
    const currVal_1:any = i1.ɵnov(_v,6).href;
    _ck(_v,5,0,currVal_0,currVal_1);
    const currVal_3:any = i1.ɵnov(_v,10).target;
    const currVal_4:any = i1.ɵnov(_v,10).href;
    _ck(_v,9,0,currVal_3,currVal_4);
  });
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9EZXZlbG9wZXIvZG9jc19zb2Z0d2FyZS9hbmd1bGFySlMvYW5ndWxhcjQtY291cnNlL2N1c3RvbS1wcm9qZWN0L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkhlbGxvIFdvcmxkITwvaDE+XHJcbjxocj5cclxuPGEgcm91dGVyTGluaz1cIi9cIj5Ib21lPC9hPlxyXG48YSByb3V0ZXJMaW5rPVwiL3VzZXJzXCI+VXNlcnM8L2E+XHJcbjxocj5cclxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUEscUNBQWlCO01BQUEsU0FDckI7TUFBQSx3RUFBSTthQUFBLDJCQUNKO01BQUE7TUFBQTtRQUFBO1FBQUE7VUFBQTtjQUFBO1VBQUE7UUFBQTtRQUFBO01BQUEsdUNBQUE7TUFBQTtNQUFBLGVBQWtCLDRDQUFRO01BQUEsdUJBQzFCO01BQUE7TUFBQTtRQUFBO1FBQUE7VUFBQTtjQUFBO1VBQUE7UUFBQTtRQUFBO01BQUEsdUNBQUE7TUFBQTtNQUFBLGVBQXVCLDZDQUFTO01BQUEsdUJBQ2hDO01BQUE7TUFBSSwwQ0FDSjtVQUFBO1VBQUEsbURBQUE7VUFBQTtjQUFBO01BQStCO0lBSDVCO0lBQUgsV0FBRyxTQUFIO0lBQ0c7SUFBSCxZQUFHLFNBQUg7SUFFQTs7SUFIQTtJQUFBO0lBQUEsV0FBQSxtQkFBQTtJQUNBO0lBQUE7SUFBQSxXQUFBLG1CQUFBOzs7O29CQ0hBO01BQUE7YUFBQTtVQUFBOzs7In0=
