/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] {\r\n  color: red;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0RldmVsb3Blci9kb2NzX3NvZnR3YXJlL2FuZ3VsYXJKUy9hbmd1bGFyNC1jb3Vyc2UvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
