/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['The Home Page']))],(null as any),(null as any));
}
export function View_HomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,
      RenderType_HomeComponent)),i0.ɵdid(1,49152,(null as any),0,i1.HomeComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const HomeComponentNgFactory:i0.ComponentFactory<i1.HomeComponent> = i0.ɵccf('ng-component',
    i1.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0RldmVsb3Blci9kb2NzX3NvZnR3YXJlL2FuZ3VsYXJKUy9hbmd1bGFyNC1jb3Vyc2UvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0RldmVsb3Blci9kb2NzX3NvZnR3YXJlL2FuZ3VsYXJKUy9hbmd1bGFyNC1jb3Vyc2UvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9EZXZlbG9wZXIvZG9jc19zb2Z0d2FyZS9hbmd1bGFySlMvYW5ndWxhcjQtY291cnNlL2N1c3RvbS1wcm9qZWN0L3NyYy9hcHAvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5UaGUgSG9tZSBQYWdlPC9oMT4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQTs7O29CQ0FKO01BQUE7OEJBQUEsVUFBQTtNQUFBOzs7In0=
