/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './users-routing,module';
import * as i2 from './users.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from './users.component';
export const UsersRoutingModuleNgFactory:i0.NgModuleFactory<i1.UsersRoutingModule> = i0.ɵcmf(i1.UsersRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.UsersComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.UsersRoutingModule,i1.UsersRoutingModule,([] as any[])),i0.ɵmpd(1024,
              i3.ROUTES,() => {
                return [[{path:'',component:i4.UsersComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLXJvdXRpbmcsbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0RldmVsb3Blci9kb2NzX3NvZnR3YXJlL2FuZ3VsYXJKUy9hbmd1bGFyNC1jb3Vyc2UvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC91c2Vycy91c2Vycy1yb3V0aW5nLG1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
