/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './users.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './users.component';
const styles_UsersComponent:any[] = [i0.styles];
export const RenderType_UsersComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_UsersComponent,data:{}});
export function View_UsersComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['Users Component here']))],(null as any),(null as any));
}
export function View_UsersComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_UsersComponent_0,
      RenderType_UsersComponent)),i1.ɵdid(1,49152,(null as any),0,i2.UsersComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const UsersComponentNgFactory:i1.ComponentFactory<i2.UsersComponent> = i1.ɵccf('ng-component',
    i2.UsersComponent,View_UsersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9EZXZlbG9wZXIvZG9jc19zb2Z0d2FyZS9hbmd1bGFySlMvYW5ndWxhcjQtY291cnNlL2N1c3RvbS1wcm9qZWN0L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovRGV2ZWxvcGVyL2RvY3Nfc29mdHdhcmUvYW5ndWxhckpTL2FuZ3VsYXI0LWNvdXJzZS9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC50cy5Vc2Vyc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Vc2VycyBDb21wb25lbnQgaGVyZTwvaDE+IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTsrQkFBQSxVQUFBO01BQUE7OzsifQ==
